name: Release Please

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-22.04
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: '${{ secrets.RELEASE_PLEASE }}'
