on:
  push:
    branches:
      - main

name: Release Please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: '${{ secrets.RELEASE_PLEASE }}'
          release-type: node
